// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxJKY6yR1tZag8pZ8gUh5VAtSz2FuoNpg',
    appId: '1:2206841105:web:daa84e4359903b107ff4b0',
    messagingSenderId: '2206841105',
    projectId: 'insta-clone-1c067',
    authDomain: 'insta-clone-1c067.firebaseapp.com',
    storageBucket: 'insta-clone-1c067.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9uX7Ykayix2MkEbb9GrSLbW-9-0vNkGA',
    appId: '1:2206841105:android:26f606316de8779b7ff4b0',
    messagingSenderId: '2206841105',
    projectId: 'insta-clone-1c067',
    storageBucket: 'insta-clone-1c067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vIlievP3orHYhmzpBQOXLoOvrlf8O90',
    appId: '1:2206841105:ios:378216865131e61e7ff4b0',
    messagingSenderId: '2206841105',
    projectId: 'insta-clone-1c067',
    storageBucket: 'insta-clone-1c067.appspot.com',
    iosBundleId: 'com.example.igclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1vIlievP3orHYhmzpBQOXLoOvrlf8O90',
    appId: '1:2206841105:ios:60024a85c3532d207ff4b0',
    messagingSenderId: '2206841105',
    projectId: 'insta-clone-1c067',
    storageBucket: 'insta-clone-1c067.appspot.com',
    iosBundleId: 'com.example.igclone.RunnerTests',
  );
}
